### ISSUE TITLE
Cloudflare IPs in some lists

### ISSUE THREAD

**Issue by rafaelsgirao** [CriticalPathSecurity/Public-Intelligence-Feeds#10]
I've noticed some Cloudflare IPs are present in some of these lists.

For example, `172.67.196.95` is present in three lists:

```
Public-Intelligence-Feeds on  master 
❯ rg 172.67.196.95
log4j.txt
8265:172.67.196.95

cps-collected-iocs.txt
19798:172.67.196.95

sans.txt
96069:172.67.196.95
```

I took this example and checked it against upstream SANS ( https://isc.sans.edu/ipinfo/172.67.196.95 ), and it's listed there solely for being on their "Public Mastodon servers" list, which I suspect is not the intended behaviour for the `sans.txt` threatlist.

**Comment by Patrick-Kelley** [comment]
I appreciate the notification. I will work to remove the issues from our feeds and send a notification to the upstream provider for the others.

**Comment by Patrick-Kelley** [comment]
The IPs have been removed and the lists will be updated at the top of the hour.
