### ISSUE TITLE
Non-malicious/suspicious data

### ISSUE THREAD

**Issue by TJTrimboli** [CriticalPathSecurity/Public-Intelligence-Feeds#11]
I have noticed some indicators present the lists would not be considered suspicious or malicious.

For example, `www.microsoft.com`, `update.microsoft.com`, and others are present in the predict.txt list. Distinguishing between those that should be Whitelisted would be helpful in making the lists more useful to those consuming the data, although, I am not sure how the Predict list selects its data.

**Comment by Patrick-Kelley** [comment]
It appears to be resolved. Please let us know if you see any other issues. We'll close them as quickly as possible.
