### ISSUE TITLE
log4j.txt takeover?

### ISSUE THREAD

**Issue by FlorianHeigl** [CriticalPathSecurity/Public-Intelligence-Feeds#2]
Hi,

the log4shell attacker ip list now has an entry (line 1) that reads `0.0.0.0` - i think this is a false positive, likely one that got planted for the kicks by a knowledgeable person.
( i know it's autogenerated, but I'm too tired to remember where to find the origina gist thread and you should also have more momentum in changing this)

**Comment by Patrick-Kelley** [comment]
Most likely. I'll get exclusions in, but it'll be tomorrow.

**Comment by shuja31** [comment]
the list also has quad1 DNS

**Comment by Patrick-Kelley** [comment]
Yes. Unfortunately, one of the source feeds that builds this list loaded false positives.  That source has been removed, permanently. Updated commit coming now.

**Comment by Patrick-Kelley** [comment]
As promised, I've built-in filtering for all no-routable addresses and have removed 0.0.0.0 and 1.1.1.1.

Unfortunately, this is an aggregation of community-data and the quality is based on that data.

I'll do my best to keep it solid.
