### ISSUE TITLE
Private addresses in log4j.txt

### ISSUE THREAD

**Issue by iainelder** [CriticalPathSecurity/Public-Intelligence-Feeds#3]
The log4j.txt list contains [private addresses](https://en.wikipedia.org/wiki/Private_network).

These should be removed, right?

```text
$ git rev-parse --short HEAD -- log4j.txt
f600b9b
$ cat log4j.txt | grep -P '^10\.' | wc -l
21
$ cat log4j.txt | grep -P '^172\.(1[6-9]|2[0-9]|3[0-1])\.' | wc -l
8
$ cat log4j.txt | grep -P '^192\.168\.' | wc -l
40
```

My workaround for now is to use the same grep expressions with the `-v` switch to exclude the the 
private addresses.

Thanks for maintaining this list.

**Comment by Patrick-Kelley** [comment]
Yes. Unfortunately, one of the source feeds that builds this list loaded false positives. That source has been removed, permanently. Updated commit coming now.

**Comment by Patrick-Kelley** [comment]
Thank you! 

The most recent commit and future ones have excluded the private ranges.

**Comment by Patrick-Kelley** [comment]
As promised, I've built-in filtering for all no-routable addresses and have removed 0.0.0.0 and 1.1.1.1.

Unfortunately, this is an aggregation of community-data and the quality is based on that data.

I'll do my best to keep it solid.

**Comment by iainelder** [comment]
Thanks for your efforts. It's helping to keep us all safe!

**Comment by ourra** [comment]
Another invalid addresses are in the localhost range (127.0.0.x); in the last version I downloaded appear both 127.0.0.1
and 127.0.0.7

Thank you for your efforts maintaining the list!

**Comment by Patrick-Kelley** [comment]
@ourra , resolved! 

You are most welcome! Thanks you helping me make it better!
