### ISSUE TITLE
What's the difference between the two Cobalt Strike IP lists?

### ISSUE THREAD

**Issue by ccie5022** [CriticalPathSecurity/Public-Intelligence-Feeds#4]
What is the difference between these two?

cobaltstrike_ips.txt
cps_cobaltstrike_ip.txt

**Comment by Patrick-Kelley** [comment]
One is sourced from https://raw.githubusercontent.com/drb-ra/C2IntelFeeds/master/feeds/IPC2s.csv (Cobaltstrike)
The other from https://threatview.io/Downloads/High-Confidence-CobaltStrike-C2%20-Feeds.txt (CobaltStrike)

My intention is to merge them. Cycles have been limited.

**Comment by Patrick-Kelley** [comment]
I've merged them into this single feed.

https://github.com/CriticalPathSecurity/Public-Intelligence-Feeds/blob/master/cps_cobaltstrike_ip.txt

I will decommission the duplicate tonight.

**Comment by ccie5022** [comment]
Thank you for protecting the inter webs
