### ISSUE TITLE
Private addresses in log4j.txt

### ISSUE THREAD

**Issue by iainelder** [CriticalPathSecurity/Public-Intelligence-Feeds#6]
Hi! Thanks for dealing with the private addresses in #3.

I noticed this morning that a few more have snuck in.

https://github.com/CriticalPathSecurity/Public-Intelligence-Feeds/blob/92faf0015b87eea95446832d4d1059e89b4f3be8/log4j.txt#L7511-L7513

**Comment by Patrick-Kelley** [comment]
Thank you, @iainelder for notifying me! 

I've adjusted the filter and you should see those removed going forward.
