### ISSUE TITLE
Removal of IP

### ISSUE THREAD

**Issue by lesleyxyz** [CriticalPathSecurity/Public-Intelligence-Feeds#9]
Dear,

As I understand the feed `drb-ra-unverified.txt` comes from the user `drb-ra` on the Threatfox platform.
However, since its detection it has been removed from Threatfox.
I've asked drb-ra to remove it [here](https://github.com/drb-ra/C2IntelFeeds/issues/20).

It has been removed yesterday, however the IP `81.82.57.202` is still in the list.
How come?

Kr,

Lesley

**Comment by Patrick-Kelley** [comment]
Happy to investigate. The IP does appear to be listed on several feeds, outside of drb-ra. 

The issue is that it is still listed. 

https://raw.githubusercontent.com/drb-ra/C2IntelFeeds/master/feeds/unverified/IPC2s-30day.csv.

Standby as I work on a resolution.

**Comment by Patrick-Kelley** [comment]
It should be removed in the next update process. I'll leave the ticket open until I can confirm.

**Comment by Patrick-Kelley** [comment]
It appears to be removed. Could you confirm on your end?

**Comment by lesleyxyz** [comment]
It is! Thank you for your swift response :)

**Comment by Patrick-Kelley** [comment]
You are most welcome!

Thanks for helping us continually improve this project!
